# Site settings
title: RabidAudio
email: charles@rabidaudio.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on music, technology, policy, startups, and anything else.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://rabid.audio" # the base hostname & protocol for your site
twitter_username: charlesjuliank
github_username:  rabidaudio

exclude:
- deploy.sh
- divshot.json
- rabidaudio.sublime-project
- rabidaudio.sublime-workspace
- node_modules
- Gruntfile.js
- README.md
- bower.json
- package.json
- components

# JS files to include from components (Bower directory)
components:
- components/jquery/dist/jquery.js
- components/lightbox/js/lightbox.js

destination: _site/blog
timezone: America/New_York

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Charles Julian Knight"
      author_contact: "http://twitter.com/charlesjuliank"

# Build settings
markdown: kramdown
