# Site settings
title: RabidAudio
email: charles@rabidaudio.com
name: Charles Julian Knight
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on music, technology, policy, startups, and anything else.
baseurl:  /blog # the subpath of your site, e.g. /blog/
imgurl:   /blog/assets/images/
jsurl:    assets/js/output.js
url: "http://rabid.audio" # the base hostname & protocol for your site

directories:
  assets: assets
  outputjs: assets/js
  sourcejs: assets/_src
  posts: _posts
  drafts: _drafts
  templates: _templates
  sass: _sass
  css: css
  templates: _templates
  plugins: _plugins
  output: _site
  layouts: _layouts
  includes: _includes


exclude:
- rabidaudio.sublime-project
- rabidaudio.sublime-workspace
- node_modules
- Gruntfile.js
- README.md
- divshot.json
- bower.json
- package.json

# JS files to include from vendor (Bower directory)
vendor:
- _vendor/jquery/dist/jquery.js
# - _vendor/lightbox/js/lightbox.js
- _vendor/inform/dist/inform.js


destination: _site/blog
timezone: America/New_York

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author:
        name:     Charles Julian Knight
        minibio:  
        twitter:  charlesjuliank
        github:   rabidaudio
        email:    charles@rabidaudio.com
        img:      http://www.gravatar.com/avatar/e3f99640d60577f72086b54087423593.png?s=200
        bitcoin:  1MCeQwp6yuL5qG54Bpn97H93ucspApbgtZ

nav:
# -
#   url: /about
#   title: About
- 
  url: /all
  title: All Posts

colors:
  green:      #Irish Sea - http://paletton.com/#uid=12Q0u0k7RBG1pW649NecqtBhVo9
    darker:   '#439748'
    dark:     '#72BA76'
    normal:   '#A0D4A3'
    light:    '#CAE8CC'
    lighter:  '#ECF7ED'
  blue:       #Plotting - http://paletton.com/#uid=13s0u0kmww-cINsi9Earsu6u3nR
    darker:   '#0D5578'
    dark:     '#1C6F98'
    main:     '#367FA3'
    light:    '#579BBC'
    lighter:  '#eef'      #86BDD7;
  grey: 
    darker:   '#424242'
    dark:     '#626262'
    main:     '#828282'
    light:    '#CCCCCC'
    lighter:  '#E8E8E8'
  default:
    darker:   '#000000'
    dark:     '#424242'
    main:     '#828282'
    light:    '#fdfdfd'
    lighter:  '#ffffff'

colormap:
  music: red
  policy: green
  hardware: blue
  software: yellow

# Build settings
markdown: kramdown

sass:
    style: :compressed