# Site settings
title: RabidAudio
email: charles@rabidaudio.com
name: Charles Julian Knight
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on music, technology, policy, startups, and anything else.
baseurl:  /blog
imgurl:   /blog/assets/images/
jsurl:    assets/js/output.js
url: "http://rabid.audio"
post_excerpt_truncate: 300

directories:
  assets    : assets
  outputjs  : assets/js
  sourcejs  : assets/_src
  posts     : _posts
  drafts    : _drafts
  templates : _templates
  sass      : _sass
  css       : css
  templates : _templates
  plugins   : _plugins
  output    : _site
  layouts   : _layouts
  includes  : _includes
  fonts     : assets/fonts


exclude:
  - rabidaudio.sublime-project
  - rabidaudio.sublime-workspace
  - node_modules
  - Gruntfile.js
  - README.md
  - divshot.json
  - bower.json
  - package.json

# JS files to include from Bower directory in desired order
vendor:
  js:
    # - _vendor/modernizr/modernizr.js
    # - _vendor/requirejs/require.js
    - _vendor/jquery/dist/jquery.js
    # - _vendor/underscore/underscore.js
    # - _vendor/imagesloaded/imagesloaded.pkgd.js
    - _vendor/inform/dist/inform.js
    # - _vendor/lightbox/js/lightbox.js
    - _vendor/javascript-last.fm-api/lastfm-api.js
    - _vendor/natural-dates/natural_dates.js
    - _vendor/javascript_utils/rand_subset.js
    # - _vendor/javascript_utils/jquery_extensions.js
  fonts:
    - fontawesome/fonts


destination: _site/blog
timezone: America/New_York

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: other
      permalink: :categories/:title/index.html
      author:
        name     : Charles Julian Knight
        # minibio  :
        img      : http://www.gravatar.com/avatar/e3f99640d60577f72086b54087423593.png?s=200
        school   : Georgia Tech
        twitter  : charlesjuliank
        email    : cjk@rabid.audio
        github   : rabidaudio
        lastfm   : rabidaudio
        google   : +CharlesJulianKnight
        # facebook :
        # linkedin :
        bitcoin  : 1MCeQwp6yuL5qG54Bpn97H93ucspApbgtZ
        # other_site:
        #   name: username
        #   url:  example.com/user/username (optional)
        #   icon: fontawesome-icon-class    (optional)
        # #or simply: custom: some text

footer_social:
  twitter: rabidaudio
  github: rabidaudio/rabid.audio

nav:
-
  url: /about
  title: About
- 
  url: /all
  title: All Posts

colors:
  green:      #Irish Sea - http://paletton.com/#uid=12Q0u0k7RBG1pW649NecqtBhVo9
    darker:   '#005100'
    dark:     '#16831C'
    main:     '#72BA76'
    light:    '#CAE8CC'
    lighter:  '#ECF7ED'
  blue:       #Plotting - http://paletton.com/#uid=13s0u0kmww-cINsi9Earsu6u3nR
    darker:   '#003752'
    dark:     '#0D5578'
    main:     '#367FA3'
    light:    '#579BBC'
    lighter:  '#EEEEFF'
  purple:
    darker:   '#28001C'
    dark:     '#630948'
    main:     '#97397B'
    light:    '#AE5D96'
    lighter:  '#F5E3F0'
  grey: 
    darker:   '#424242'
    dark:     '#626262'
    main:     '#828282'
    light:    '#CCCCCC'
    lighter:  '#E8E8E8'
  default:
    darker:   '#000000'
    dark:     '#424242'
    main:     '#828282'
    light:    '#fdfdfd'
    lighter:  '#ffffff'
  red:
    darker:   '#7E0018'
    dark:     '#BF0E30'
    main:     '#DF2D4F'
    light:    '#EE5371'
    lighter:  '#FFD7DF'

colormap:
  music:    red
  policy:   green
  hardware: purple
  software: blue

#map tags to categories
tagmap:
  music:
    - genre
    - last.fm
    - music
    - new music
    - RIAA
    - car audio
  policy:
    - free software movement
    - piracy
    - soapbox
    - tech policy
  software:
    - computing
    - dsp
    - Android
    - networking
    - server
    - software
    - web development
    - windows
    - javascript
  hardware:
    - arduino
    - bluetooth
    - electronics
    - wearables


# Build settings
markdown: kramdown

sass:
  style: :compressed