# Site settings
title: RabidAudio
email: charles@rabidaudio.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on music, technology, policy, startups, and anything else.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://rabid.audio" # the base hostname & protocol for your site
twitter_username: charlesjuliank
github_username:  rabidaudio

exclude: [deploy.sh, divshot.json, cheatsheet.md]
destination: _site/blog
timezone: America/New_York

# Build settings
markdown: kramdown
