# Site settings
title: RabidAudio
email: charles@rabidaudio.com
name: Charles Julian Knight
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on music, technology, policy, startups, and anything else.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://rabid.audio" # the base hostname & protocol for your site
twitter_username: charlesjuliank
github_username:  rabidaudio

exclude:
- rabidaudio.sublime-project
- rabidaudio.sublime-workspace
- node_modules
- Gruntfile.js
- README.md
- divshot.json
- bower.json
- package.json

# JS files to include from vendor (Bower directory)
vendor:
- _vendor/jquery/dist/jquery.js
# - _vendor/lightbox/js/lightbox.js
- _vendor/inform/dist/inform.js


destination: _site/blog
timezone: America/New_York

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Charles Julian Knight"
      author_contact: "http://twitter.com/charlesjuliank"
      author_img: http://www.gravatar.com/avatar/e3f99640d60577f72086b54087423593.png?s=200

# Build settings
markdown: kramdown
