name: Deploy to GitHub pages

on:
  push:
    branches:
      - main

jobs:
  deploy_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"
      - run: npm install

      - name: Build
        run: bin/bridgetown deploy
        env:
          BRIDGETOWN_ENV: production

      - name: Deploy
        run: npm run publish
        env:
          CHICY_DEPLOY_KEY: ${{ secrets.CHICY_DEPLOY_KEY }}
