name: Deploy to GitHub pages

on:
  push:
    branches:
      - main

jobs:
  deploy_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "yarn"
      - run: yarn install

      - name: Build
        run: bin/bridgetown deploy
        env:
          BRIDGETOWN_ENV: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.BLOG_DEPLOY_TOKEN }}
          publish_dir: ./output
          external_repository: rabidaudio/rabidaudio.github.io
          publish_branch: main
          cname: rabid.audio
